// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameApi.Database;

#nullable disable

namespace VideoGameApi.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    [Migration("20241124064953_seeding data")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameApi.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Santa Monica Studio",
                            Platform = "PS5",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "God of War: Ragnarok"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "343 Industries",
                            Platform = "Xbox Series X",
                            Publisher = "Xbox Game Studios",
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "FromSoftware",
                            Platform = "PC",
                            Publisher = "Bandai Namco Entertainment",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "Mojang Studios",
                            Platform = "PC",
                            Publisher = "Microsoft",
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 6,
                            Developer = "CD Projekt Red",
                            Platform = "PC",
                            Publisher = "CD Projekt",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 7,
                            Developer = "Rockstar Games",
                            Platform = "PS4",
                            Publisher = "Rockstar Games",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 8,
                            Developer = "Nintendo",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "Super Mario Odyssey"
                        },
                        new
                        {
                            Id = 9,
                            Developer = "Blizzard Entertainment",
                            Platform = "PC",
                            Publisher = "Blizzard Entertainment",
                            Title = "Overwatch 2"
                        },
                        new
                        {
                            Id = 10,
                            Developer = "Ubisoft Montreal",
                            Platform = "Xbox Series X",
                            Publisher = "Ubisoft",
                            Title = "Assassin's Creed Valhalla"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
